# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "bucket_for_tf"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/vpc/terraform.tfstate"
    region         = "us-east-1"
  }
}
